spring.application.name=JPA_HomeWork

spring.datasource.url = jdbc:mysql://localhost:3306/
spring.datasource.username = root
spring.datasource.password = root

#cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto = update
#mostra log do sql gerado pelo jpa 
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
